# docker-compose.yml
version: "3.3"

services:
  postgres-app:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}

  camunda-app:
    restart: always
    build: ./com.alanda.camunda.services
    image: camunda-app
    env_file: ./com.alanda.camunda.services/.env
    depends_on:
      - postgres-app
    ports:
      - ${CAMUNDA_APP_PORT}:${CAMUNDA_APP_PORT}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-app:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

  process-app:
    restart: always
    build: ./com.alanda.process.services
    image: process-app
    hostname: process-app
    env_file: ./com.alanda.process.services/.env
    ports:
      - ${PROCESS_APP_PORT}:${PROCESS_APP_PORT}
    environment:
      - PROCESS_MANAGER_CAMUNDA_API=${PROCESS_MANAGER_CAMUNDA_API}
      - PROCESS_MANAGER_CAMUNDA_UPLOAD=${PROCESS_MANAGER_CAMUNDA_UPLOAD}
      - PROCESS_MANAGER_CAMUNDA_DUPLICATE_FILTERING=${PROCESS_MANAGER_CAMUNDA_DUPLICATE_FILTERING}
    depends_on:
      - camunda-app
    links:
      - camunda-app
    volumes:
      - ./ressources:/ressources